### ISSUE TITLE
Excellent ! 

### ISSUE THREAD

**Issue by douglasduteil** [robianmcd/angular-next#3]
Hi @robianmcd 

I just discovered your work here and it's pretty good :)
I'm actually doing a similar thing with just ES6 (instead of AtStrcipt) and 6to5 (instead of Traceur).

Keep up you're good work !
Douglas.

**Comment by robianmcd** [comment]
@douglasduteil cool! Is your project up on github? I'd love to take a look

**Comment by douglasduteil** [comment]
It's just a plunker poke for now. Check this out : http://plnkr.co/GRsQJF

**Comment by robianmcd** [comment]
Looks pretty cool! Interesting to see how similar some pieces of code are.
